---
env:
  shell: bash
  secrets-manager:
    DOCKERHUB_USERNAME: DockerHubSecret:dockerhub_username
    DOCKERHUB_PASSWORD: DockerHubSecret:dockerhub_password
phases:
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t angular-node ."
      - "docker tag angular-node:latest public.ecr.aws/e2c9a1x6/angular-node:latest"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push public.ecr.aws/e2c9a1x6/angular-node:latest"
  pre_build:
    commands:
      - "echo Logging in to Docker Hub..."
      - "docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD"
version: 0.1
