---
env:
  shell: bash
  secrets-manager:
    DOCKERHUB_USERNAME: DockerHubSecret:dockerhub_username
    DOCKERHUB_PASSWORD: DockerHubSecret:dockerhub_password
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - pip install --upgrade awscli
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t angular-node ."
      - "docker tag angular-node:latest public.ecr.aws/e2c9a1x6/angular-node:latest"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "aws "
      - "docker push public.ecr.aws/e2c9a1x6/angular-node:latest"
  pre_build:
    commands:
      - "echo Logging in to Docker Hub..."
      - "docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD"
      - "aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/e2c9a1x6"
version: 0.1
