version: 0.2
phases:
  pre-build:
    commands:
      - npm install newman --global
  build:
    commands:
      - cd postman
      - newman run -r html,cli REMPApi.postman_collection --reporter-html-export report.html

artifacts:
  files:
    - report.html
